-- public."UserTransactions" definition

-- Drop table

-- DROP TABLE public."UserTransactions";

CREATE TABLE public."UserTransactions" (
                                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                           "name" text NOT NULL,
                                           "transactionValue" numeric NOT NULL,
                                           "date" timestamp NOT NULL,
                                           CONSTRAINT "PK_UserTransactions" PRIMARY KEY (id)
);